import { NextRequest, NextResponse } from "next/server";
import { supabaseRequest } from "@/lib/supabase";

export const runtime = "nodejs";

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);

  const mode = searchParams.get("hub.mode");
  const token = searchParams.get("hub.verify_token");
  const challenge = searchParams.get("hub.challenge");

  const verifyToken = process.env.META_VERIFY_TOKEN;

  if (mode === "subscribe" && token === verifyToken && challenge) {
    console.log("WEBHOOK VERIFIED");
    return new Response(challenge, { status: 200 });
  }

  return new Response("Forbidden", { status: 403 });
}

async function sendMessengerMessage(recipientId: string, text: string) {
  const token = process.env.META_PAGE_ACCESS_TOKEN;
  const version = process.env.META_GRAPH_API_VERSION;

  if (!token || !version) {
    throw new Error(
      "META_PAGE_ACCESS_TOKEN and META_GRAPH_API_VERSION are required."
    );
  }

  const response = await fetch(
    `https://graph.facebook.com/${version}/me/messages`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        recipient: { id: recipientId },
        message: { text },
      }),
    }
  );

  const data = await response.json();

  console.log("SEND API RESPONSE:", data);

  if (!response.ok) {
    throw new Error(
      `Messenger API error: ${JSON.stringify(data)}`
    );
  }

  return data;
}

async function findRule(messageText: string) {
  const normalized = messageText.trim().toLowerCase();

  const rules = await supabaseRequest(
    `keyword_rules?keyword=eq.${encodeURIComponent(normalized)}&enabled=eq.true&select=id,keyword,response&limit=1`
  );

  return rules[0] ?? null;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    console.log("=================================");
    console.log("MESSENGER WEBHOOK RECEIVED");
    console.log(JSON.stringify(body, null, 2));
    console.log("=================================");

    for (const entry of body.entry ?? []) {
      for (const messaging of entry.messaging ?? []) {
        // Ignore messages generated by the Page itself.
        if (messaging.message?.is_echo) continue;

        const senderId = messaging.sender?.id;
        const messageText = messaging.message?.text;

        if (!senderId || !messageText) continue;

        console.log("SENDER ID:", senderId);
        console.log("MESSAGE:", messageText);

        const rule = await findRule(messageText);

        if (rule) {
          console.log(
            `MATCHED KEYWORD "${rule.keyword}" -> sending response`
          );

          await sendMessengerMessage(senderId, rule.response);
        }
      }
    }

    return NextResponse.json({ received: true });
  } catch (error) {
    console.error("Webhook error:", error);

    // Return 200 so Meta does not repeatedly retry a malformed event.
    return NextResponse.json({ received: true }, { status: 200 });
  }
}
